same job's diffenrent tasks should compare task's priority
volcano-sh/volcano pull request #1452
Opened 2021-05-06 02:07 UTC by lowang-bh

priority plugin's preemptableFn has 2 conditions to preempt: Preemption between Jobs and Preemption between Task within Job; so same job's diffenrent tasks should compare task's priority

Signed-off-by: lowang_bh <lhui_wang@163.com>

2021-05-06 03:37 UTC, Thor-wl approved these changes

2021-05-07 02:11 UTC, wpeng102 commented
/lgtm

2021-05-07 02:20 UTC, shinytang6 requested changes

2021-05-07 02:20 UTC, shinytang6 commented on pkg/scheduler/plugins/priority/priority.go
> +			} else { // same job's diffenrent tasks should compare task's priority
typo here, rest lgtm
/lgtm

2021-05-07 03:22 UTC, Thor-wl commented
/lgtm

2021-05-07 03:23 UTC, merged