support oversubscription in volcano framework
volcano-sh/volcano pull request #1566
Opened 2021-06-28 00:59 UTC by wpeng102

https://github.com/volcano-sh/volcano/issues/1348

Our team is working on cluster resource oversubscription on volcano as a internal feature. When some application request more resources than it need, publish those "idle" resources to the scheduler to dispatch preemptable tasks and reclaim them when there's CPU pressure. 
So, we need volcano framework 1) support to record the oversubscription resource. 2) support plugin can drop preempt/reclaim decision in some cases.

Currently, we use 
`volcano.sh/oversubscription` to record if node is enable oversubscription feature
`volcano.sh/oversubscription-cpu` to record cpu oversubscription number
`volcano.sh/oversubscription-memory` to record memory oversubscription number
`volcano.sh/offline-job-evicting` to record if node has stop oversubscription resoruce due to resource pressure.

Introduce second return value for `reclaimableFns` and `preemptableFns` , if plugin return `abstain (0 value)`, it meas this plugin drop the preempt/reclaim decision.

2021-06-28 01:10 UTC, Thor-wl commented
/lgtm

2021-06-28 02:47 UTC, jasonliu747 requested changes

2021-06-28 02:47 UTC, jasonliu747 commented on pkg/scheduler/plugins/tdm/tdm.go
>  	tutil "volcano.sh/volcano/pkg/scheduler/plugins/util"
duplicate import

2021-06-30 02:26 UTC, Thor-wl approved these changes

2021-06-30 02:27 UTC, merged

2021-06-30 03:07 UTC, william-wang approved these changes
/lgtm
/approve