Add GPU Numbers Predicates
volcano-sh/volcano pull request #1692
Opened 2021-08-23 15:31 UTC by peiniliu

Support specify GPU numbers for pod resource requests [issue#1440](https://github.com/volcano-sh/volcano/issues/1440)

Currently, Volcano only supports specified GPU share memory. Specified GPU number is not supported. This pr supports defining GPU numbers for pod resource requests. You can check the design doc https://github.com/peiniliu/volcano/blob/dev/docs/user-guide/how_to_use_gpu_number.md for more details.

2021-08-24 02:39 UTC, jasonliu747 commented
Hi @peiniliu , thanks for your contribution. Please fix the DCO check.

2021-08-24 08:23 UTC, william-wang commented
@jasonliu747 Really hope this feature can be involved into v1.4. I have not got a gpu env. do you have gpu environment for verification?

2021-08-25 03:01 UTC, jasonliu747 commented
@william-wang let me double check and get back to you!

2021-08-30 02:11 UTC, william-wang commented
@peiniliu Rebase and submit the pr again.

2021-08-30 10:29 UTC, peiniliu commented
@jasonliu747 @william-wang  
Hi, 
the pr has been updated! 
Best,
Peini

2021-09-09 09:08 UTC, zamog commented
This PR will fix #1686 ?

2021-10-15 09:48 UTC, peiniliu commented
this PR supports users to define GPU number predicates via container level resource requirements using the 'volcano.sh/gpu-numbers'. For provided issue, you may look at the queue and preempt or reclaim actions.

2021-11-27 03:54 UTC, Thor-wl commented
This feature is very useful and important! Let's take a review for it. @allReviewers

2021-11-29 07:43 UTC, hwdef commented
Can it support splitting a GPU. For example, use one-half of the GPU.

2021-11-29 07:45 UTC, hwdef commented
What if the gpu models are different?
If If there are three 2080 and three 3080 on one machine.The gpu number is set to 2. How to specify which gpu to use?

2021-11-29 08:43 UTC, peiniliu commented
> Can it support splitting a GPU. For example, use one-half of the GPU.

thanks for this comment! As far as I understand, splitting a GPU should use our gpu-sharing configuration. GPU number now only supports numbers in integer (even if we change it to support float number, I think the backend should always require integer+1 number of GPUs, for example, configure 1.2 will ask 2 GPUs).

2021-11-29 08:48 UTC, Thor-wl commented
/cc @peiniliu Peini, pls resolve the confilcts.

2021-11-29 08:52 UTC, peiniliu commented
> What if the gpu models are different? If If there are three 2080 and three 3080 on one machine.The gpu number is set to 2. How to specify which gpu to use?

This is a nice question! Indeed now we can not distinguish different type of GPUs. GPUs will be allocated by their id in sequence. In this case, the first two GPUs will be selected.

I think now the node status and GPU device info do not support heterogeneous GPU devices. Volcano knows the numbers/memory of GPUs through the device plugin.

$ kubectl get node {node name} -oyaml
...
status:
  addresses:
  - address: 172.17.0.3
    type: InternalIP
  - address: volcano-control-plane
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: 123722704Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8174332Ki
    pods: "110"
    volcano.sh/gpu-memory: "89424"
    volcano.sh/gpu-number: "8"    # GPU resource
  capacity:
    cpu: "4"
    ephemeral-storage: 123722704Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8174332Ki
    pods: "110"
    volcano.sh/gpu-memory: "89424"
    volcano.sh/gpu-number: "8"   # GPU resource

2021-11-29 08:55 UTC, peiniliu commented
> /cc @peiniliu Peini, pls resolve the conflicts.

let's solve all the technical questions first :), I ll do this before merging!

2021-11-29 09:33 UTC, hwdef commented
> > Can it support splitting a GPU. For example, use one-half of the GPU.
> 
> thanks for this comment! As far as I understand, splitting a GPU should use our gpu-sharing configuration. GPU number now only supports numbers in integer (even if we change it to support float number, I think the backend should always require integer+1 number of GPUs, for example, configure 1.2 will ask 2 GPUs).

Do we have gpu-sharing related documents? Sorry, I don’t know much about volcano's gpu. I think the combination of these two functions into one function will be more user-friendly.

2021-11-29 09:34 UTC, hwdef commented
> > What if the gpu models are different? If If there are three 2080 and three 3080 on one machine.The gpu number is set to 2. How to specify which gpu to use?
> 
> This is a nice question! Indeed now we can not distinguish different type of GPUs. GPUs will be allocated by their id in sequence. In this case, the first two GPUs will be selected.
> 
> I think now the node status and GPU device info do not support heterogeneous GPU devices. Volcano knows the numbers/memory of GPUs through the device plugin.
> 
> ```shell
> $ kubectl get node {node name} -oyaml
> ...
> status:
>   addresses:
>   - address: 172.17.0.3
>     type: InternalIP
>   - address: volcano-control-plane
>     type: Hostname
>   allocatable:
>     cpu: "4"
>     ephemeral-storage: 123722704Ki
>     hugepages-1Gi: "0"
>     hugepages-2Mi: "0"
>     memory: 8174332Ki
>     pods: "110"
>     volcano.sh/gpu-memory: "89424"
>     volcano.sh/gpu-number: "8"    # GPU resource
>   capacity:
>     cpu: "4"
>     ephemeral-storage: 123722704Ki
>     hugepages-1Gi: "0"
>     hugepages-2Mi: "0"
>     memory: 8174332Ki
>     pods: "110"
>     volcano.sh/gpu-memory: "89424"
>     volcano.sh/gpu-number: "8"   # GPU resource
> ```

ok,I see. This is not a big problem.

2021-11-29 09:54 UTC, peiniliu commented
> > > Can it support splitting a GPU. For example, use one-half of the GPU.
> > 
> > 
> > thanks for this comment! As far as I understand, splitting a GPU should use our gpu-sharing configuration. GPU number now only supports numbers in integer (even if we change it to support float number, I think the backend should always require integer+1 number of GPUs, for example, configure 1.2 will ask 2 GPUs).
> 
> Do we have gpu-sharing related documents? Sorry, I don’t know much about volcano's gpu. I think the combination of these two functions into one function will be more user-friendly.

Hi,

yes, I think our first version to implement this was to combine them both. But I remember we asked in real cases that users usually use only one type of GPU configuration. @william-wang 
Also I attached here the gpu-sharing -> https://github.com/volcano-sh/volcano/blob/master/docs/user-guide/how_to_use_gpu_sharing.md

Best,
Peini

2021-11-29 11:06 UTC, 5had3z commented
Before this intergrated, I just wanted to bring up the point of why not just properly intergrate with nvidia's gpu operator? I made a fork of volcano and made modifications to peiniliu's code so that I can just use nvidia.com/gpu requests and nodeSelector to select the type of GPU node I want to run on. I haven't had any issues so far with this.

2021-12-06 06:57 UTC, k82cn commented
Let's create a PR for design doc :)

2022-05-04 03:23 UTC, shinytang6 requested changes
hi @peiniliu, I have a design question to ask:
If the user only turns on GPUNumberEnable, it seems that the functionally is similar to the nvidia device plugin. I understand the difference is:
* The real gpu allocation of nvidia device plugin is done at the device plugin level
* volcano does gpu id allocation at the scheduling level, and the volcano device plugin is only responsible for delivering the environment variables that scheduler patches?

Am l right? If so, is it possible to register volcano.sh/gpu-number as a resource in the volcano device plugin, just like nvidia device plugin, and do health management there. Then I understand that no special treatment is required in the scheduling layer, have you considered this way?

2022-05-06 09:30 UTC, peiniliu commented
Hi @shinytang6,

Thanks for your comments.

You are right, the real GPU allocation is done at the device plugin level(but in volcano case is volcano device plugin instead of the official Nvidia one)

See here the way the volcano device plugin allocates the GPU: [volcano` device plugin GPU allocation]((https://github.com/volcano-sh/devices/blob/b8725b77abef5255a9fc419085f8f194ca687a39/pkg/plugin/nvidia/server.go#L311)). Basically, the plugin is reading the GPU allocation results from what volcano scheduler patched to the pod annotation.
`id := GetGPUIDFromPodAnnotation(candidatePod)`

If to do in way as u said, we may need to change the plugin's allocation function to distinguish one card or multiple cards for gpu-share or gpu-number scenarios in volcano. 
I see the design doc [#1779](https://github.com/volcano-sh/volcano/pull/1779), they implemented this. If everyone vote for this change, I think I could change the implementation to follow this new device plugin. :)

But from my point of view, there are still some values to make the allocation in the scheduling layer. Given the scheduler has already known the GPU status, it is easy to decide if the allocation could work or not in advance.

Best,
Peini

2022-05-07 05:47 UTC, shinytang6 commented
> Hi @shinytang6,
> 
> Thanks for your comments.
> 
> You are right, the real GPU allocation is done at the device plugin level(but in volcano case is volcano device plugin instead of the official Nvidia one)
> 
> See here the way the volcano device plugin allocates the GPU: [volcano device plugin GPU allocation](https://github.com/volcano-sh/devices/blob/b8725b77abef5255a9fc419085f8f194ca687a39/pkg/plugin/nvidia/server.go#L311). Basically, the plugin is reading the GPU allocation results from what volcano scheduler patched to the pod annotation. `id := GetGPUIDFromPodAnnotation(candidatePod)`
> 
> If to do in way as u said, we may need to change the plugin's allocation function to distinguish one card or multiple cards for gpu-share or gpu-number scenarios in volcano. I see the design doc [#1779](https://github.com/volcano-sh/volcano/pull/1779), they implemented this. If everyone vote for this change, I think I could change the implementation to follow this new device plugin. :)
> 
> But from my point of view, there are still some values to make the allocation in the scheduling layer. Given the scheduler has already known the GPU status, it is easy to decide if the allocation could work or not in advance.
> 
> Best, Peini

@peiniliu Thanks for the clarification, it makes sense to me. But my concern is that if `volcano.sh/gpu-number` is not registered as a resource, it is difficult to do health management, currently volcano device plugin just patches the number of volcano.sh/gpu-number when initialization which is not so robust.

2022-05-08 19:00 UTC, peiniliu commented
> > Hi @shinytang6,
> > Thanks for your comments.
> > You are right, the real GPU allocation is done at the device plugin level(but in volcano case is volcano device plugin instead of the official Nvidia one)
> > See here the way the volcano device plugin allocates the GPU: [volcano device plugin GPU allocation](https://github.com/volcano-sh/devices/blob/b8725b77abef5255a9fc419085f8f194ca687a39/pkg/plugin/nvidia/server.go#L311). Basically, the plugin is reading the GPU allocation results from what volcano scheduler patched to the pod annotation. `id := GetGPUIDFromPodAnnotation(candidatePod)`
> > If to do in way as u said, we may need to change the plugin's allocation function to distinguish one card or multiple cards for gpu-share or gpu-number scenarios in volcano. I see the design doc [#1779](https://github.com/volcano-sh/volcano/pull/1779), they implemented this. If everyone vote for this change, I think I could change the implementation to follow this new device plugin. :)
> > But from my point of view, there are still some values to make the allocation in the scheduling layer. Given the scheduler has already known the GPU status, it is easy to decide if the allocation could work or not in advance.
> > Best, Peini
> 
> @peiniliu Thanks for the clarification, it makes sense to me. But my concern is that if `volcano.sh/gpu-number` is not registered as a resource, it is difficult to do health management, currently volcano device plugin just patches the number of volcano.sh/gpu-number when initialization which is not so robust.

Hi, 
yes, currently 'volcano.sh/gpu-number' is registered as resources in the scheduler layer, but not in the device plugin. I agree to improve the device plugin and do health management there. By the way, I ve seen a lot of topics in the community to enhance the GPU, we may consider those designs together in order to avoid conflicts. I would like to join some talks and make contributions there.
Best,
Peini

2022-05-11 12:34 UTC, shinytang6 commented
> > > Hi @shinytang6,
> > > Thanks for your comments.
> > > You are right, the real GPU allocation is done at the device plugin level(but in volcano case is volcano device plugin instead of the official Nvidia one)
> > > See here the way the volcano device plugin allocates the GPU: [volcano device plugin GPU allocation](https://github.com/volcano-sh/devices/blob/b8725b77abef5255a9fc419085f8f194ca687a39/pkg/plugin/nvidia/server.go#L311). Basically, the plugin is reading the GPU allocation results from what volcano scheduler patched to the pod annotation. `id := GetGPUIDFromPodAnnotation(candidatePod)`
> > > If to do in way as u said, we may need to change the plugin's allocation function to distinguish one card or multiple cards for gpu-share or gpu-number scenarios in volcano. I see the design doc [#1779](https://github.com/volcano-sh/volcano/pull/1779), they implemented this. If everyone vote for this change, I think I could change the implementation to follow this new device plugin. :)
> > > But from my point of view, there are still some values to make the allocation in the scheduling layer. Given the scheduler has already known the GPU status, it is easy to decide if the allocation could work or not in advance.
> > > Best, Peini
> > 
> > 
> > @peiniliu Thanks for the clarification, it makes sense to me. But my concern is that if `volcano.sh/gpu-number` is not registered as a resource, it is difficult to do health management, currently volcano device plugin just patches the number of volcano.sh/gpu-number when initialization which is not so robust.
> 
> Hi, yes, currently 'volcano.sh/gpu-number' is registered as resources in the scheduler layer, but not in the device plugin. I agree to improve the device plugin and do health management there. By the way, I ve seen a lot of topics in the community to enhance the GPU, we may consider those designs together in order to avoid conflicts. I would like to join some talks and make contributions there. Best, Peini

That will be great! 
/cc @Thor-wl  for review

2022-07-12 07:37 UTC, Thor-wl commented on docs/user-guide/how_to_use_gpu_number.md
> +  volcano.sh/predicate-time: “1593764466550835304”
Is it necessary to provide the `predicate-time`? Besides, it seems to be a time stamp which is not so readable.

2022-07-12 07:37 UTC, Thor-wl commented on docs/user-guide/how_to_use_gpu_number.md
> +  VOLCANO_GPU_TOTAL: “15109” # GPU memory of the card
IC, so perhaps it is more readable to name the GPU memory of the card as `VOLCANO_GPU_MEMORY_TOTAL`.

2022-07-12 07:37 UTC, Thor-wl commented on pkg/scheduler/api/device_info.go
> +
Just a small advice, the following expression maybe more brief.
```go
// isIdleGPU check if the device is idled.
func (g *GPUDevice) isIdleGPU() bool {
    return g.PodMap == nil || len(g.PodMap) == 0
}
```
It is not something matters.

2022-07-12 07:37 UTC, Thor-wl commented on pkg/scheduler/api/device_info.go
> +	for _, container := range pod.Spec.Containers {
Please also take initContainer into consideration.

2022-07-12 07:37 UTC, Thor-wl commented on pkg/scheduler/api/pod_info.go
> +			ids := strings.Split(value, ",")
Are there some validations about the format of this annotation?

2022-07-15 10:22 UTC, peiniliu commented
I changed docs because the device plugin now sets GPU share as default, as well as fixed some env names and the flow image,
I think now this is ready as well.

2022-07-19 01:54 UTC, Thor-wl reviewed
Except for the consideration of initContianer, it is OK to me generally.

2022-07-21 11:38 UTC, shinytang6 requested changes

2022-07-21 11:38 UTC, shinytang6 commented on docs/user-guide/how_to_use_gpu_number.md
> +          volcano.sh/gpu-number: 1 # requesting 2 gpu cards
requesting 1 gpu cards

2022-07-21 11:38 UTC, shinytang6 commented on docs/user-guide/how_to_use_gpu_sharing.md
> +* By default volcano device plugin supports shared GPUs, users do not need to config volcano device plugin. Default setting is the same as setting --gpu-strategy=number. For more information [volcano
please use the volcano official link here

2022-07-21 11:38 UTC, shinytang6 commented on pkg/scheduler/plugins/predicates/predicates.go
> +		klog.Errorf("can not define true in both gpu sharing and gpu number")
l think it's better to use `klog.Fatal` here

2022-07-21 11:38 UTC, shinytang6 commented on pkg/scheduler/plugins/predicates/predicates.go
>  			if predicate.gpuSharingEnable && api.GetGPUResourceOfPod(pod) > 0 {
let's rename GetGPUResourceOfPod to GetGPUMemoryOfPod

2022-07-21 11:40 UTC, shinytang6 commented on docs/user-guide/how_to_use_gpu_number.md
> +![gpu_number](../images/gpu-number.png)
Kebe-API-Server => Kube-API-Server

2022-07-23 13:27 UTC, peiniliu commented
I fixed those comments.

2022-07-25 02:15 UTC, shinytang6 requested changes

2022-07-25 02:15 UTC, shinytang6 commented on docs/user-guide/how_to_use_gpu_sharing.md
> +
the link is 404

2022-07-27 08:22 UTC, shinytang6 reviewed
Generally LGTM. 
/cc @Thor-wl @william-wang Please take another look

2022-07-28 01:39 UTC, Thor-wl commented on pkg/scheduler/api/device_info.go
> +	for _, container := range pod.Spec.Containers {
BTW, is this commnet resolved? @peiniliu

2022-07-28 01:41 UTC, Thor-wl reviewed
BTW, is the comment about `initContainer` resolved?

2022-07-28 07:58 UTC, peiniliu commented
> BTW, is the comment about `initContainer` resolved?

as explained, currently device plugin does not fit multiple containers. as well as the initContainer is designed for some start scripts which may not request GPUs. Well, I think the important part is the device plugin, once it supports, the GPU usage for initContainer can be added.

2022-07-28 08:19 UTC, Thor-wl commented
> > BTW, is the comment about `initContainer` resolved?
> 
> as explained, currently device plugin does not fit multiple containers. as well as the initContainer is designed for some start scripts which may not request GPUs. Well, I think the important part is the device plugin, once it supports, the GPU usage for initContainer can be added.

IC, that's OK for me.

2022-07-28 08:19 UTC, Thor-wl commented
/lgtm

2022-07-29 10:19 UTC, peiniliu commented
I removed some unrelated info in the doc after the presentation.

2022-07-30 01:02 UTC, Thor-wl commented
/lgtm

2022-08-15 07:26 UTC, Thor-wl approved these changes

2022-08-15 07:39 UTC, shinytang6 approved these changes
/lgtm

2022-08-15 07:52 UTC, merged

2022-09-07 12:04 UTC, WingkaiHo commented on pkg/scheduler/plugins/predicates/predicates.go
> +				ids := predicateGPUbyMemory(pod, nodeInfo)
share gpu pod only need to one gpu id, but predicateGPUbyMemory reture all gpu id which are suitable for the pod.