support reserved node
volcano-sh/volcano pull request #1821
Opened 2021-11-04 09:58 UTC by qiankunli

for example, my k8s cluster has 10 nodes (10 gpu per node), 5 for training, 5 for serving, I want use volcano schedule tfjob/pytorchjob/vcjob on training nodes. use default-scheduler  schedule online pod on serving nodes.

it it work by setting nodeSelector or nodeAffinity to pod,  but it is not properly when considering queue.

if there are  two queue: queue1(weight=1) and queue2 (weight=1),  it is overused if queue1 used 40 gpu, but it's weight  resource is 50, so if queue2 want use 20 gpu, reclaimable mechanism will not work.

so it is necessary to limit volcano scheduler that  it is can only work on training nodes, not all nodes in cluster.  

so I add `work-node-label` args for volcano scheduler, in following example,  volcano can only work on the node which has label `node-role:training` or `node-role:dev`.

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: volcano-scheduler
  namespace: xdl-system
  labels:
    app: volcano-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volcano-scheduler
  template:
    metadata:
      labels:
        app: volcano-scheduler
    spec:
      serviceAccount: volcano-scheduler
      containers:
        - name: volcano-scheduler
          image: harbor.ximalaya.local/xdl/vc-scheduler:v1.4.0-xmly-node
          args:
            - --work-node-label=node-role:training
            - --work-node-label=node-role:dev
            - --logtostderr
            - --scheduler-conf=/volcano.scheduler/volcano-scheduler.conf
            - -v=5
            - 2>&1
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: scheduler-config
              mountPath: /volcano.scheduler
      volumes:
        - name: scheduler-config
          configMap:
            name: volcano-scheduler-configmap
```

2021-11-06 02:01 UTC, Thor-wl commented
@qiankunli Pls `go fmt xxx`

2021-11-12 00:58 UTC, k82cn commented on cmd/scheduler/app/options/options.go
> +	fs.StringSliceVar(&s.WorkNodeLabels, "work-node-label", nil, "volcano only work with the labeled node, like: --work-node-label=volcano.sh/role:train --work-node-label=volcano.sh/role:serving")
Prefer to check those labels in `CheckOptionOrDie` :)

2021-11-12 02:09 UTC, Thor-wl commented
> if there are two queue: queue1(weight=1) and queue2 (weight=1), it is overused if queue1 used 40 gpu, but it's weight resource is 50, so if queue2 want use 20 gpu, reclaimable mechanism will not work.

Sorry for not clear why queue1 is overused if it used 40 gpu for it's weight is 1.

2021-11-12 02:17 UTC, Thor-wl commented
I agree with the design to select nodes which volcnao can charge with node label, but it's not a flexible implementation way to specify `work-node` as arguments in start command. Suggent to consider set them in the configuration of scheduler.

2021-11-12 02:23 UTC, Thor-wl commented
BTW, this feature is import and useful. Suggest to add a doc for that.

2021-11-14 02:42 UTC, qiankunli commented
> BTW, this feature is import and useful. Suggest to add a doc for that.

ok, I add a doc    https://github.com/qiankunli/volcano/blob/feature/support_reserved_node/docs/design/node-selector.md

2021-11-15 03:16 UTC, Thor-wl commented
> > BTW, this feature is import and useful. Suggest to add a doc for that.
> 
> ok, I add a doc https://github.com/qiankunli/volcano/blob/feature/support_reserved_node/docs/design/node-selector.md

OK. Suggest to submit a PR and add the doc to docs/design

2021-11-17 01:18 UTC, Thor-wl commented
/cc @qiankunli Pls take a check about the influence with existing features.

2021-11-17 01:18 UTC, Thor-wl commented
/hold

2021-11-27 03:35 UTC, Thor-wl commented
/hold cancel

2021-11-27 03:37 UTC, Thor-wl commented
/cc @reviewers This feature is important and meaningful. I plan to take it into v1.5. Pls give your review comments. THX.

2021-11-27 08:20 UTC, shinytang6 commented
> /cc @allReviewers This feature is important and meaningful. I plan to take it into v1.5. Pls give your review comments. THX.

It's better to set up some sig or wg(working group) under volcano org, then you can @ all members to review :) @Thor-wl

2021-11-27 08:22 UTC, shinytang6 requested changes

2021-11-27 08:22 UTC, shinytang6 commented on pkg/scheduler/cache/cache.go
> +	"time"
please help make the ci happy first

2021-11-27 17:19 UTC, jasonliu747 reviewed
/hold

2021-11-29 01:33 UTC, Thor-wl commented
> 

Good idea! This event will take into schedule in Q1 2022. Need all the contributors' advices.

2021-12-13 03:57 UTC, shinytang6 commented
ls this ready for review? /cc @qiankunli

2021-12-20 09:05 UTC, shinytang6 requested changes

2021-12-20 09:05 UTC, shinytang6 commented on pkg/scheduler/cache/cache.go
> +			//sc.nodeSelectorLabels[nodeSelectorLabel] = ""
pls remove the unused comments

2021-12-20 09:05 UTC, shinytang6 commented on cmd/scheduler/app/options/options.go
> +	NodeSelector []string
NodeSelector => NodeSelectors

2021-12-20 12:32 UTC, shinytang6 reviewed
lgtm overall :)

2021-12-21 06:19 UTC, Thor-wl commented
/approve Thanks for your contribution!

2021-12-21 06:21 UTC, Thor-wl commented
/lgtm

2021-12-21 06:39 UTC, merged