[fix]add nodeSelector design doc
volcano-sh/volcano pull request #1834
Opened 2021-11-16 04:56 UTC by qiankunli

Signed-off-by: bert.li <qiankun.li@qq.com>
design doc for #1821

2021-11-17 01:26 UTC, Thor-wl commented on docs/design/node-selector.md
> +if there are two queue: queue1(weight=1) and queue2 (weight=1), it is overused if queue1 used 40 gpu, but it's weight resource is 50 (100 * 1/2), so if queue2 want use 20 gpu, reclaimable mechanism w
If there are totally 100 GPUs in the cluster, the deserved resource for queue1 and queue2 are both 50 GPUS. Why is it overused if queue1 used 40 GPUs? BTW, please make the format and grammar of the doc more canonical.

2021-11-17 01:26 UTC, Thor-wl commented on docs/design/node-selector.md
> +```yaml
Sugeest to add comment about the configuration to point out what should be foucsed on.

2021-11-17 01:26 UTC, Thor-wl commented on docs/design/node-selector.md
> +      node-role: training,dev
Pls separate `node-role` to different items

2021-11-17 01:26 UTC, Thor-wl commented on docs/design/node-selector.md
> +volcano use nodeInformer to get all node list in k8s cluster. so we can filter the node list by nodeSelector label.
This is implementation part and suggest to give more details about what should be done clearly.

2021-11-17 01:29 UTC, Thor-wl commented
/hold

2021-11-17 08:49 UTC, shinytang6 requested changes
Two suggestions:
1. pods should also be filtered by specified nodes
2. I recommend putting the configuration of node-selector in the scheduler parameters

2021-11-17 08:55 UTC, Thor-wl commented
> Two suggestions:
> 
> 1. pods should also be filtered by specified nodes
> 2. I recommend putting the configuration of node-selector in the scheduler parameters

If node-selector is put as scheduer parameters, may it be not so flexible when make modifications?

2021-11-17 08:59 UTC, shinytang6 commented
> > Two suggestions:
> > 
> > 1. pods should also be filtered by specified nodes
> > 2. I recommend putting the configuration of node-selector in the scheduler parameters
> 
> If node-selector is put as scheduer parameters, may it be not so flexible when make modifications?

The configuration file is hot updated, but it will not resync after the update, which may cause some of the changed nodes not be added to the cache

2021-11-17 09:12 UTC, qiankunli commented
> > > Two suggestions:
> > > 
> > > 1. pods should also be filtered by specified nodes
> > > 2. I recommend putting the configuration of node-selector in the scheduler parameters
> > 
> > 
> > If node-selector is put as scheduer parameters, may it be not so flexible when make modifications?
> 
> The configuration file is hot updated, but it will not resync after the update, which may cause some of the changed nodes not be added to the cache
I have changed the `schedule.conf` file watch code to watch the changed nodeSelector config

2021-11-17 09:12 UTC, qiankunli commented
I have changed the schedule.conf file watch code to watch the changed nodeSelector config

2021-11-17 09:23 UTC, Thor-wl commented
/hold cancel

2021-11-17 09:37 UTC, Thor-wl commented
> > > Two suggestions:
> > > 
> > > 1. pods should also be filtered by specified nodes
> > > 2. I recommend putting the configuration of node-selector in the scheduler parameters
> > 
> > 
> > If node-selector is put as scheduer parameters, may it be not so flexible when make modifications?
> 
> The configuration file is hot updated, but it will not resync after the update, which may cause some of the changed nodes not be added to the cache

Well, yes, that may be a problem.

2021-11-22 12:02 UTC, shinytang6 reviewed
lgtm overall

2021-11-27 03:31 UTC, Thor-wl commented
/approve

2021-11-27 17:26 UTC, jasonliu747 reviewed
lgtm overall, except some grammar issues.
I'll give more comments on Monday~

2021-12-13 01:32 UTC, Thor-wl commented
/lgtm

2021-12-13 01:33 UTC, merged