Add tensorflow job plugin
volcano-sh/volcano pull request #1874
Opened 2021-12-02 08:28 UTC by LuBingtan

Signed-off-by: lubingtan <lubingtan@126.com>

reference: https://github.com/volcano-sh/volcano/pull/1806

Hi all~ this PR is a part of implementation for the proposal **Machine Learning Framework Plugins** https://github.com/volcano-sh/volcano/pull/1806 (or distributed framework plugins)

Because there are multiple plugins to be implemented, which will bring large size of changes. I prefer to split this implementation into several phases:

- [ ] Add Tensorflow job plugin (i.e. this PR)
- [ ] Add MPI job plugin.
- [ ] Add PyTorch job plugin.
- [ ] Add MXNet job plugin
- [ ] Add default task dependency policy for framework plugins after this https://github.com/volcano-sh/volcano/pull/1833 merged

Moreover, there are more AI frameworks, such as [MindSpore](https://github.com/mindspore-ai/mindspore), [PaddlePaddle](https://github.com/PaddlePaddle/Paddle), etc.  Any contributions for various framework plugins are welcomed.

2021-12-06 06:37 UTC, shinytang6 requested changes

2021-12-06 06:37 UTC, shinytang6 commented on pkg/webhooks/admission/jobs/mutate/mutate_job.go
> +}
It's better to add some comments or log here to clarify that tensorflow plugin depends on svc plugin )

2021-12-11 07:36 UTC, LuBingtan commented
@shinytang6 
Thans for your review! Already updated.

2021-12-12 13:33 UTC, shinytang6 reviewed
Thx, looks good to me :)
waiting for others to take another look

2021-12-13 00:50 UTC, k82cn commented
LGTM overall :)

/approve

2021-12-13 01:11 UTC, Thor-wl commented
/lgtm

2021-12-13 01:12 UTC, merged