fix that parse the scheduler configuration argument with blank error
volcano-sh/volcano pull request #2061
Opened 2022-03-08 06:58 UTC by Thor-wl

ref：https://github.com/volcano-sh/volcano/issues/2053
The root reason is that argument is collected with interface{} and its value is valid type. Namely, it cannot be converted to string first or it will be error. Unfortunely, the original code ignore the error with `_` and the `value` gets the default value "".
Signed-off-by: Thor-wl <13164644535@163.com>

2022-03-08 09:39 UTC, hwdef reviewed
/lgtm

2022-03-09 06:27 UTC, shinytang6 requested changes
Others LGTM

2022-03-09 06:27 UTC, shinytang6 commented on pkg/scheduler/framework/arguments.go
> +		klog.Warningf("Could not parse argument: %s for key %s to int", argv, key)
pls use %v for argv

2022-03-10 06:31 UTC, Thor-wl commented on pkg/scheduler/framework/arguments.go
> +		klog.Warningf("Could not parse argument: %s for key %s to int", argv, key)
OK. Let me upate that.

2022-03-11 06:07 UTC, william-wang approved these changes
/lgtm

2022-03-11 06:07 UTC, merged