remove redundant parameter for rescheduling
volcano-sh/volcano pull request #2242
Opened 2022-05-17 11:43 UTC by Thor-wl

Signed-off-by: Thor-wl <13164644535@163.com>

2022-05-17 11:55 UTC, wpeng102 approved these changes
/lgtm

2022-05-17 12:14 UTC, william-wang requested changes

2022-05-17 12:14 UTC, william-wang commented on docs/design/rescheduling.md
> +                  "cpu" : 20
If i use `cpu` other than `"cpu"`, does it work?

2022-05-18 01:25 UTC, hwdef reviewed
/lgtm

2022-05-18 01:25 UTC, merged