chore: update the volcano imagePullPolicy from IfNotPresent
volcano-sh/volcano pull request #2254
Opened 2022-05-21 03:21 UTC by Aju100

Resolves: #2070

2022-05-21 03:25 UTC, Aju100 commented
/assign @shinytang6

2022-05-21 09:39 UTC, Thor-wl commented on installer/volcano-development.yaml
> +            - --tls-cert-file=imagePullPolicy/admission.local.config/certificates/tls.crt
Thanks for your contribution! Please update for the arm yaml files as well

2022-05-21 10:33 UTC, Aju100 commented
I have updated on arm file too.

2022-05-23 03:57 UTC, Thor-wl commented
/lgtm

2022-05-23 07:14 UTC, shinytang6 commented
/hold

2022-05-23 07:16 UTC, shinytang6 requested changes
Thx for your contributions.
But l think what you need to change are the files under `installer/helm/chart/*` and then use `make update-development-yaml` to generate `volcano-development-*` files automatically.

2022-05-24 03:30 UTC, Aju100 commented
@shinytang6 Resolves the automated generated yaml file for policy one

2022-05-24 03:31 UTC, Aju100 commented
/assign @shinytang6

2022-05-26 02:21 UTC, Thor-wl commented
/approve

2022-05-26 05:00 UTC, shinytang6 approved these changes
/approve

2022-07-06 02:40 UTC, Thor-wl commented
/cc @Aju100 This PR is already ready to be merged. Please resolve the conflicts. I'll merge it later. Thanks!

2022-07-11 01:54 UTC, Thor-wl commented
/lgtm

2022-08-17 04:11 UTC, Thor-wl commented
@Aju100 Hi. Are there some updates again? If not, I'll close this PR later.

2022-10-12 11:13 UTC, closed without merging