[cherry-pick for release-1.9]Fix annotatin too long 1.9
volcano-sh/volcano pull request #3356
Opened 2024-03-18 02:26 UTC by guoqinwill

cherry-pick：https://github.com/volcano-sh/volcano/pull/3347

2024-03-18 07:57 UTC, shinytang6 requested changes

2024-03-18 07:57 UTC, shinytang6 commented on Makefile
> +  # generate volcano jobflow crd yaml without description to avoid yaml size limit when using `kubectl apply`
pls format the comments

2024-03-18 08:41 UTC, guoqinwill commented on Makefile
> +  # generate volcano jobflow crd yaml without description to avoid yaml size limit when using `kubectl apply`
done

2024-03-19 09:59 UTC, wangyang0616 commented
/LGTM

2024-03-25 07:57 UTC, hwdef commented
/lgtm

2024-04-02 11:12 UTC, william-wang approved these changes

2024-04-02 11:12 UTC, merged