fix enable node device score plugin
volcano-sh/volcano pull request #3578
Opened 2024-07-10 07:26 UTC by coldzerofear

The node device rating is currently not usable, fix it now

2024-07-10 10:40 UTC, coldzerofear commented
/assign @shinytang6

2024-07-11 02:01 UTC, shinytang6 requested changes
Pls fix the DCO, the changes lgtm

2024-12-18 04:07 UTC, archlitchi commented
yes:) thanks for fixing

/lgtm

2024-12-18 05:06 UTC, lowang-bh commented on pkg/scheduler/plugins/deviceshare/deviceshare.go
> +  args.GetString(&dsp.schedulePolicy, SchedulePolicyArgument)
Please use space insead of Tab.

2025-02-25 08:21 UTC, Monokaix commented
/ok-to-test

2025-02-25 08:47 UTC, Monokaix commented
Hi, are you still working on this, please rebase master and fix comments.

2025-05-06 02:18 UTC, closed without merging